# Generated by Django 4.1.7 on 2023-02-17 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lp', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('input_LP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input', to='calculator.lp')),
                ('output_LP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output', to='calculator.lp')),
            ],
        ),
    ]
